import test from 'node:test';
import assert from 'node:assert/strict';
import {openBrowserSave,writeBrowserSave,SAVE_KEY,MODE_KEY} from '../lib/browser-save.mjs';
const memory=()=>{const rows=new Map();return {getItem:key=>rows.get(key)??null,setItem:(key,value)=>rows.set(key,value)};};
test('signed-out play persists and reload restores browser progress',()=>{const storage=memory(),first=openBrowserSave(storage,'a');first.state.thoughts=123;first.state.lifetime=456;const saved=writeBrowserSave(storage,first.state,'a',first.revision);assert.equal(saved.revision,2);const restored=openBrowserSave(storage,'b');assert.equal(restored.state.thoughts,123);assert.equal(restored.state.lifetime,456);assert.equal(storage.getItem(MODE_KEY),'browser');});
test('new game resets a browser journey and invalidates older windows',()=>{const storage=memory(),first=openBrowserSave(storage,'a');first.state.wisdom=10;writeBrowserSave(storage,first.state,'a',first.revision);const fresh=openBrowserSave(storage,'b',true);assert.equal(fresh.state.wisdom,0);assert.equal(fresh.state.thoughts,0);assert.throws(()=>writeBrowserSave(storage,first.state,'a',first.revision),e=>e.status===409);assert.equal(openBrowserSave(storage,'c').state.wisdom,0);});
test('separate browsers have separate progress, with no shared anonymous account',()=>{const a=memory(),b=memory(),first=openBrowserSave(a,'a');first.state.thoughts=1000;writeBrowserSave(a,first.state,'a',first.revision);assert.equal(openBrowserSave(b,'b').state.thoughts,0);});
test('corrupt saves are preserved unless explicitly reset',()=>{const storage=memory();storage.setItem(SAVE_KEY,'bad save');assert.throws(()=>openBrowserSave(storage,'a'));assert.equal(storage.getItem(SAVE_KEY),'bad save');assert.equal(openBrowserSave(storage,'a',true).state.thoughts,0);});
test('failed storage writes report failure instead of claiming progress saved',()=>{const storage=memory(),first=openBrowserSave(storage,'a');storage.setItem=()=>{throw Error('Quota exceeded');};assert.throws(()=>writeBrowserSave(storage,first.state,'a',first.revision),/Quota/);});
