import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../lib/game-engine.mjs';
const wealthy=()=>Object.assign(E.fresh(),{thoughts:1e20,era:14,highestEra:14,discovered:Array(15).fill(true),counts:Array(15).fill(4)});
test('fresh start can recover from losing every thinker',()=>{const s=E.fresh();s.counts.fill(0);assert.equal(E.rate(s),0);assert.equal(E.think(s,1000),1);assert.equal(E.think(s,1010),0);for(let i=1;i<15;i++)E.think(s,1000+i*120);assert.ok(E.buy(s,0));assert.ok(E.rate(s)>0);});
test('wagers double or lose only the selected thinker and respect cap',()=>{const s=wealthy();const other=s.counts[1];assert.equal(E.wager(s,0,()=>0).after,8);assert.equal(E.wager(s,0,()=>.999).after,0);assert.equal(s.counts[1],other);s.counts[0]=E.MAX_COUNT;assert.equal(E.wager(s,0,()=>0),null);});
test('all three automation slots independently buy, wager, bank and rebuild',()=>{const s=wealthy();for(let i=0;i<3;i++)assert.ok(E.addSlot(s));for(let i=0;i<3;i++)assert.ok(E.configureSlot(s,i,{enabled:true,seed:4,target:8}));for(let i=0;i<3;i++)E.tick(s,2,()=>0);assert.deepEqual(s.counts.slice(0,3),[8,8,8]);for(let i=0;i<3;i++)E.tick(s,2,()=>.999);assert.deepEqual(s.counts.slice(0,3),[8,8,8]);for(let i=0;i<3;i++)E.configureSlot(s,i,{target:64,enabled:true});for(let j=0;j<3;j++)E.tick(s,2,()=>.999);assert.deepEqual(s.counts.slice(0,3),[0,0,0]);for(let i=0;i<3;i++)E.tick(s,2,()=>.999);assert.ok(s.counts.slice(0,3).every(n=>n>0));});
test('slot allocation avoids duplicates after reassignment; upgrade isolation',()=>{const s=wealthy();E.addSlot(s);E.configureSlot(s,0,{thinker:1});E.addSlot(s);assert.equal(s.slots[1].thinker,0);assert.equal(E.configureSlot(s,1,{thinker:1}),false);assert.equal(E.configureSlot(s,1,{seed:8,target:4}),false);assert.ok(E.upgradeSlot(s,0,'luck'));assert.equal(s.slots[1].luck,0);});
test('paradigms add; metaphilosophies multiply; wisdom is a separate diminishing factor',()=>{const s=wealthy();s.era=2;s.meta=2;s.wisdom=100;const f=E.factors(s);assert.equal(f.paradigm,2);assert.equal(f.meta,1.6*1.7);assert.equal(f.wisdom,2.2);s.wisdom=400;assert.equal(E.factors(s).wisdom,3.4);});

test('early thinkers cannot bypass ages, while existing discoveries remain usable',()=>{const s=E.fresh();s.thoughts=1e12;assert.ok(E.buy(s,1));assert.equal(E.buy(s,2),false);s.era=1;assert.equal(E.buy(s,2),false);s.era=2;assert.ok(E.buy(s,2));assert.equal(E.buy(s,3),false);s.era=3;assert.equal(E.buy(s,3),false);assert.ok(E.advance(s));assert.ok(E.buy(s,3));s.era=1;s.counts[3]=0;assert.ok(E.buy(s,3),'A previously discovered thinker can be rebuilt after a loss.');});

test('truths consume ink without reducing wisdom, transcend preserves only intended state',()=>{const s=wealthy();s.wisdom=20;s.ink=20;s.run=1e12;E.checkAchievements(s);const a=s.achievements.length;assert.ok(E.buyTruth(s,0));assert.equal(s.wisdom,20);assert.equal(s.ink,18);const reward=E.transcend(s);assert.ok(reward.wisdom>0);assert.equal(s.era,0);assert.equal(s.meta,0);assert.equal(s.slots.length,0);assert.equal(s.thoughts,300);assert.equal(s.counts[1],1);assert.equal(s.achievements.length,a);assert.equal(s.highestEra,14);assert.ok(s.wisdom>20);});
test('save validation rejects corruption; clean reset removes all permanent progress',()=>{const s=wealthy();assert.deepEqual(E.validateState(s).counts,s.counts);assert.throws(()=>E.validateState({...s,thoughts:Infinity}));assert.throws(()=>E.validateState({...s,counts:[-1]}));assert.throws(()=>E.validateState({...s,era:100}));assert.throws(()=>E.validateState({...s,achievements:[99]}));assert.equal(E.fresh().wisdom,0);assert.equal(E.fresh().truths.length,0);});
test('all progression remains finite under extreme count and long-run values',()=>{const s=wealthy();s.counts.fill(E.MAX_COUNT);s.meta=5;s.wisdom=1e50;for(let i=0;i<100;i++)E.tick(s,2);assert.ok(Number.isFinite(s.thoughts));assert.ok(Number.isFinite(E.rate(s)));assert.ok(E.clickValue(s)>0);assert.equal(E.format(Infinity),'—');});


test('removed mini-games cannot run; old saves preserve rewards and retire active challenges',()=>{const old=wealthy();delete old.wagerStats;delete old.idleSeconds;old.wins=19;old.losses=21;old.achievements=[24,25];old.challenge={active:true};old.paradox={active:true};const s=E.validateState(old);assert.equal(s.challenge,null);assert.equal(s.paradox,null);assert.equal(s.wagerStats.legacyWins,19);assert.equal(s.wagerStats.legacyLosses,21);assert.equal(E.visibleAchievementCount(s),0);assert.equal(E.factors(s).achievements,1.01);assert.equal(E.startPolice,undefined);assert.equal(E.startParadox,undefined);assert.equal(E.availableAchievements().length,28);});
test('wager accounting counts events, not thinkers, and separates manual from automated',()=>{const s=wealthy();E.wager(s,0,()=>0);E.wager(s,0,()=>1);E.addSlot(s);E.wager(s,1,()=>0,s.slots[0]);E.wager(s,1,()=>1,s.slots[0]);assert.deepEqual(E.wagerSummary(s),{wins:2,losses:2,total:4,percent:50});assert.deepEqual(s.wagerStats,{manualWins:1,manualLosses:1,autoWins:1,autoLosses:1,legacyWins:0,legacyLosses:0});assert.deepEqual(E.validateState(s).wagerStats,s.wagerStats);assert.throws(()=>E.validateState({...s,wins:3}));});
test('manual and automated odds stay close to the stated chance over 100000 wagers',()=>{for(const automated of [false,true]){const s=wealthy();s.odds=8;E.addSlot(s);const slot=automated?s.slots[0]:undefined;if(slot)slot.luck=4;let x=12345;const rng=()=>((x=(x*1664525+1013904223)>>>0)/4294967296);for(let i=0;i<100000;i++){s.counts[0]=4;E.wager(s,0,rng,slot);}assert.equal(s.wins+s.losses,100000);assert.ok(Math.abs(s.wins/100000-E.chance(s,slot))<.005);assert.ok(E.wagerSummary(s).percent<61);}});
test('Start/Pause preserves drafts, banked targets stop and can be raised to resume',()=>{const s=wealthy();E.addSlot(s);assert.ok(E.configureSlot(s,0,{enabled:true,target:8}));E.tick(s,2,()=>0);E.tick(s,2,()=>0);E.tick(s,1,()=>0);assert.equal(s.counts[0],8);assert.equal(s.slots[0].enabled,false);assert.match(E.automationStatus(s,s.slots[0]),/Target reached/);assert.equal(E.configureSlot(s,0,{enabled:true}),false);assert.ok(E.configureSlot(s,0,{enabled:true,target:32}));assert.ok(E.configureSlot(s,0,{enabled:false}));const counts=[...s.counts];for(let i=0;i<10;i++)E.tick(s,2,()=>0);assert.deepEqual(s.counts,counts);assert.match(E.automationStatus(s,s.slots[0]),/Paused/);assert.ok(E.configureSlot(s,0,{enabled:true}));for(let i=0;i<6;i++)E.tick(s,2,()=>0);assert.equal(s.counts[0],32);assert.equal(s.slots[0].enabled,false);});
test('passive production rests without investment and recovers on buying or wagering',()=>{const s=E.fresh();s.achievements=E.availableAchievements().map(a=>a.i);const r=E.rate(s);for(let i=0;i<120;i++)E.tick(s,2);assert.ok(Math.abs(s.thoughts-r*(60+120*.2+60*.02))<1e-8);assert.equal(E.activeIncome(s),r*.02);assert.ok(E.buy(s,0));assert.equal(E.activeIncome(s),E.rate(s));s.idleSeconds=180;s.discovered[1]=true;E.wager(s,0,()=>1);assert.equal(s.idleSeconds,0);});
test('four hours away grants modest capped income without buying, wagering or advancing',()=>{const s=wealthy();s.era=11;s.thoughts=0;s.savedAt=1000;E.addSlot(s);const r=E.rate(s),counts=[...s.counts];const out=E.offline(s,1000+4*3600000);assert.equal(out.seconds,3600);assert.equal(out.thoughts,Math.min(r*36,E.eraCost(s)*.1));assert.ok(s.thoughts<=E.eraCost(s)*.1);assert.deepEqual(s.counts,counts);assert.equal(s.era,11);assert.equal(s.wins+s.losses,0);assert.equal(s.idleSeconds,14400);assert.equal(E.offline(s,1000).thoughts,0);});
test('Classical no longer unlocks later generations of thinkers or a cheap next age',()=>{const s=wealthy();s.era=4;s.discovered=s.discovered.map((_,i)=>i<=3);assert.equal(E.canDiscover(s,4),false);assert.equal(E.canDiscover(s,5),false);assert.equal(E.eraCost(s),6000000);s.era=5;assert.ok(E.canDiscover(s,4));assert.equal(E.canDiscover(s,5),false);});
test('synthesis remains in late game without either removed mini-game',()=>{const s=E.fresh();assert.equal(E.synthesize(s),false);Object.assign(s,wealthy());s.counts[2]=s.counts[7]=s.counts[12]=100;s.insight=100;assert.ok(E.synthesize(s));assert.equal(s.synthesis,1);assert.equal(s.counts[2],92);assert.equal(s.insight,50);});
