export const THINKERS = [
 ['Curious Wanderer',10,1,'A question where there was only silence.'],['Storyteller',90,5,'A small fire. A story larger than the night.'],['Priest',600,24,'Searching for the sacred in the everyday.'],['Philosopher',4000,115,'Even certainty deserves a question.'],['Alchemist',28000,550,'What if matter could become possibility?'],['Scientist',200000,2600,'The universe leaves clues.'],['Enlightenment Thinker',1500000,12500,'Let reason open every door.'],['Academic',12000000,60000,'Knowledge grows when it is shared.'],['Psychologist',100000000,290000,'A universe behind every pair of eyes.'],['Computer Scientist',850000000,1400000,'Thought finds a new language.'],['AI Researcher',7500000000,6800000,'Can a question learn to ask itself?'],['Quantum Thinker',70000000000,33000000,'Possibility refuses to choose.'],['Posthuman',700000000000,160000000,'The mind outgrows its first home.'],['Galactic Philosopher',7500000000000,780000000,'Every star, another perspective.'],['Cosmic Deity',90000000000000,3800000000,'The universe begins to wonder about itself.']
].map(([name,cost,rate,desc],i)=>({name,cost:Math.round(cost*1.4**Math.max(0,i-4)),rate,desc,i}));
export const ERAS=[
 ['The Age of Curiosity','The first question','Somewhere beneath the stars, a mind begins to wonder.'],['Animism','A living world','The forest is no longer silent. Everything has a story.'],['Mythology','Stories in the sky','We name the stars, and the stars become a world.'],['Monotheism','A single light','Many questions gather around one impossible answer.'],['Classical Philosophy','The examined life','On the steps of an academy, certainty meets curiosity.'],['Scholasticism','Faith meets reason','A thousand candles illuminate the margins of a book.'],['Renaissance Humanism','The world reawakens','Art, inquiry, and human possibility share the same sky.'],['Rationalism','The architecture of reason','From a single premise, an extraordinary world unfolds.'],['Empiricism','Look a little closer','The smallest observation can change everything.'],['Idealism','A world within','Perhaps the mind is not a window, but the landscape.'],['Modernism','A century of possibility','New machines. New questions. New ways to be human.'],['Existentialism','Choose your meaning','Beneath an indifferent sky, a life becomes your own.'],['Postmodernism','Beyond the grand story','Every mirror reveals another point of view.'],['Computationalism','The thinking universe','A cathedral of information reaches toward infinity.'],['Cosmic Pantheism','We are the question','The stars and the observer were never truly separate.']
].map(([name,subtitle,desc],i)=>({name,subtitle,desc,i,cost:i<5?[0,450,6000,60000,600000][i]:Math.round(600000*10**(i-4)),bonus:i<5?[0,.4,.6,.8,1][i]:1+i*.2}));
export const META=[['Divine Reason',6,3e6,1.6],['Empiricism of Truth',8,9e7,1.7],['Multiplicity of Truths',10,3e9,1.8],['Probabilistic Ontology',12,1e11,1.9],['Omniconsciousness',14,4e12,2]].map(([name,era,cost,multi],i)=>({name,era,cost,multi,i}));
export const TRUTHS=[['Persistent Memory',2,'Begin each new run with 300 thoughts and a Storyteller.'],['Innate Wisdom',3,'A separate ×1.15 production multiplier.'],['Rapid Insight',3,'Think grants ×1.5 thoughts.'],['Ancient Knowledge',4,'Paradigms cost 20% less, in every run.'],['Wager Mastery',5,'Manual wagers gain +2 percentage points. Automation keeps its own odds.'],['Infinite Potential',6,'Cosmic Synthesis can be completed 30 times instead of 20.']].map(([name,cost,desc],i)=>({name,cost,desc,i}));
export const ACHIEVEMENTS=[['Cogito','Make your first thought.'],['Spark','Generate 100 thoughts.'],['Illumination','Generate 10,000 thoughts.'],['Enlightenment','Generate one million thoughts.'],['Transcendent Mind','Generate one billion thoughts.'],['Cosmic Awareness','Generate one trillion thoughts.'],['Small Circle','Own 10 of a thinker.'],['Symposium','Own 50 of a thinker.'],['Academy','Own 500 of a thinker.'],['Polymath','Discover all 15 thinkers.'],['Paradigm Pioneer','Enter Animism.'],['Era Walker','Reach Scholasticism.'],['History Complete','Reach Cosmic Pantheism.'],['Leap of Faith','Win a wager.'],['Fortune Favors','Win 25 wagers.'],['Philosopher King','Win 150 wagers.'],['Meta Thinker','Discover a metaphilosophy.'],['Ultimate Truth','Discover all five metaphilosophies.'],['Automation','Build an automater.'],['Reborn','Transcend once.'],['Eternal Thinker','Transcend five times.'],['Diligent Mind','Think 500 times.'],['Thought Stream','Produce 1,000 thoughts per second.'],['Thought Torrent','Produce one million thoughts per second.']].map(([name,desc],i)=>({name,desc,i}));
export const MAX_COUNT=1e9;
ACHIEVEMENTS.push(...[['Unconquered Mind','Defeat the Thought Police.',14],['Beautiful Contradiction','Resolve a paradox.',15],['A New Constellation','Complete a cosmic synthesis.',16],['Independent Minds','Build all three automaters.',13],['Many Lives','Collect all six Eternal Truths.',19],['The Long View','Complete ten cosmic syntheses.',4]].map(([name,desc,art],j)=>({name,desc,i:24+j,art})));
export const fresh=()=>({version:1,thoughts:0,run:0,lifetime:0,counts:[1,...Array(14).fill(0)],discovered:[true,...Array(14).fill(false)],era:0,highestEra:0,meta:0,focus:0,odds:0,slots:[],wisdom:0,ink:0,truths:[],achievements:[],runs:0,clicks:0,wins:0,losses:0,policeWins:0,paradoxWins:0,synthesis:0,insight:0,policeAt:0,paradoxAt:0,challenge:null,paradox:null,savedAt:Date.now(),lastClick:0,playtime:0,idleSeconds:0,wagerStats:{manualWins:0,manualLosses:0,autoWins:0,autoLosses:0,legacyWins:0,legacyLosses:0}});
const cap=x=>Math.min(1e100,Math.max(0,Number.isFinite(x)?x:0));
export function factors(s){return {paradigm:1+ERAS.slice(1,s.era+1).reduce((a,e)=>a+e.bonus,0),meta:META.slice(0,s.meta).reduce((a,e)=>a*e.multi,1),wisdom:1+.12*Math.sqrt(s.wisdom),truth:s.truths.includes(1)?1.15:1,synthesis:1+s.synthesis*.12,achievements:1+s.achievements.length*.005};}
export const effectiveCount=n=>n<=512?n:512+Math.sqrt(n-512)*16;
export const baseRate=s=>s.counts.reduce((a,n,i)=>a+effectiveCount(n)*THINKERS[i].rate,0);
export const multiplier=s=>Object.values(factors(s)).reduce((a,b)=>a*b,1);
export const rate=s=>cap(baseRate(s)*multiplier(s));
export const activeIncome=s=>rate(s)*(s.idleSeconds<60?1:s.idleSeconds<180?.2:.02);
const engage=s=>{s.idleSeconds=0;};
export const availableAchievements=()=>ACHIEVEMENTS.filter(a=>a.i!==24&&a.i!==25);
export const visibleAchievementCount=s=>s.achievements.filter(i=>i!==24&&i!==25).length;
export function wagerSummary(s){const total=s.wins+s.losses;return {wins:s.wins,losses:s.losses,total,percent:total?s.wins/total*100:null};}
export const clickValue=s=>Math.max((1+s.focus*2)*factors(s).paradigm,rate(s)*(.025+s.focus*.003))*(s.truths.includes(2)?1.5:1);
export const buyCost=(s,i)=>s.counts[i]>=MAX_COUNT?Infinity:THINKERS[i].cost*1.75**Math.min(s.counts[i],1000);
export const eraCost=s=>s.era>=14?Infinity:ERAS[s.era+1].cost*(s.truths.includes(3)?.8:1);
export const focusCost=s=>Math.round(35*6**s.focus);
export const oddsCost=s=>Math.round(500*8**s.odds);
export const wisdomGain=s=>s.era<6?0:Math.max(1,Math.floor((s.era-4)*1.2+Math.max(0,Math.log10(Math.max(1,s.run))-6)));
export const chance=(s,slot)=>slot?Math.min(.54,.48+slot.luck*.015):Math.min(.60,.5+s.odds*.01+(s.truths.includes(4)?.02:0));
export function gain(s,n){n=cap(n);s.thoughts=cap(s.thoughts+n);s.run=cap(s.run+n);s.lifetime=cap(s.lifetime+n);}
const pay=(s,n)=>{if(!Number.isFinite(n)||n<0||s.thoughts<n)return false;s.thoughts-=n;return true;};
export const thinkerEra=i=>[0,0,2,4,5,6,7,8,9,10,11,12,12,13,14][i]??14;
// Keep existing discoveries usable when a balancing update moves their unlock.
export const canDiscover=(s,i)=>!!THINKERS[i]&&(s.discovered[i]||i===0||(s.discovered[i-1]&&s.era>=thinkerEra(i)));
export function buy(s,i){if(!Number.isInteger(i)||!THINKERS[i]||!canDiscover(s,i)||!pay(s,buyCost(s,i)))return false;s.counts[i]++;s.discovered[i]=true;engage(s);return true;}
export function wager(s,i,rng=Math.random,slot){if(!THINKERS[i]||s.counts[i]<1||s.counts[i]>=MAX_COUNT||!s.discovered[1])return null;const before=s.counts[i],win=rng()<chance(s,slot);s.counts[i]=win?Math.min(MAX_COUNT,before*2):0;s[win?'wins':'losses']++;s.wagerStats[(slot?'auto':'manual')+(win?'Wins':'Losses')]++;engage(s);return {win,before,after:s.counts[i]};}
export function think(s,now=Date.now()){if(now-s.lastClick<110)return 0;s.lastClick=now;const n=clickValue(s);gain(s,n);s.clicks++;if(s.era>=8)s.insight=Math.min(100,s.insight+1);return n;}
export function advance(s){if(s.era>=14||!s.discovered[Math.max(0,s.era-1)]||!pay(s,eraCost(s)))return false;s.era++;s.highestEra=Math.max(s.highestEra,s.era);engage(s);return true;}
export function upgrade(s,kind){if(kind==='focus'&&s.focus<20&&pay(s,focusCost(s))){s.focus++;engage(s);return true;}if(kind==='odds'&&s.discovered[2]&&s.odds<8&&pay(s,oddsCost(s))){s.odds++;engage(s);return true;}if(kind==='meta'&&META[s.meta]&&s.era>=META[s.meta].era&&pay(s,META[s.meta].cost)){s.meta++;engage(s);return true;}return false;}
export const slotCost=s=>[18000,220000,3000000][s.slots.length]??Infinity;
export function addSlot(s){if(s.era<4||s.slots.length>=3||!pay(s,slotCost(s)))return false;s.slots.push({thinker:s.discovered.findIndex((known,i)=>known&&!s.slots.some(slot=>slot.thinker===i)),seed:4,target:64,enabled:false,buySpeed:0,wagerSpeed:0,luck:0,buyTimer:0,wagerTimer:0,last:'Ready'});engage(s);return true;}
export const slotUpgradeCost=(slot,k)=>Math.round(12000*5**slot[k]);
export function upgradeSlot(s,i,k){const slot=s.slots[i];if(!slot||!['buySpeed','wagerSpeed','luck'].includes(k)||slot[k]>=4||!pay(s,slotUpgradeCost(slot,k)))return false;slot[k]++;engage(s);return true;}
export function configureSlot(s,i,patch){const slot=s.slots[i];if(!slot)return false;const thinker=patch.thinker??slot.thinker;if(!Number.isInteger(thinker)||!s.discovered[thinker])return false;if(s.slots.some((x,j)=>j!==i&&x.thinker===thinker))return false;const seed=patch.seed??slot.seed,target=patch.target??slot.target;if(!Number.isInteger(seed)||seed<1||seed>32||!Number.isInteger(target)||target<=seed||target>MAX_COUNT)return false;if(patch.enabled!==undefined&&typeof patch.enabled!=='boolean')return false;if(patch.enabled&&s.counts[thinker]>=target)return false;if(thinker!==slot.thinker){slot.buyTimer=0;slot.wagerTimer=0;}Object.assign(slot,{thinker,seed,target,enabled:patch.enabled??slot.enabled});return true;}
export function checkAchievements(s){const max=Math.max(...s.counts);const tests=[s.lifetime>=1,s.lifetime>=100,s.lifetime>=1e4,s.lifetime>=1e6,s.lifetime>=1e9,s.lifetime>=1e12,max>=10,max>=50,max>=500,s.discovered.every(Boolean),s.highestEra>=1,s.highestEra>=5,s.highestEra>=14,s.wins>=1,s.wins>=25,s.wins>=150,s.meta>=1,s.meta>=5,s.slots.length>=1,s.runs>=1,s.runs>=5,s.clicks>=500,rate(s)>=1000,rate(s)>=1e6,false,false,s.synthesis>=1,s.slots.length===3,s.truths.length===6,s.synthesis>=10];const added=[];tests.forEach((v,i)=>{if(v&&!s.achievements.includes(i)){s.achievements.push(i);added.push(i);}});return added;}
export function automationStatus(s,slot){
 const count=s.counts[slot.thinker];
 if(count>=slot.target)return 'Target reached · raise Stop at to continue';
 if(!slot.enabled)return 'Paused · press Start';
 if(count<slot.seed)return s.thoughts<buyCost(s,slot.thinker)?'Waiting for '+format(buyCost(s,slot.thinker))+' thoughts':'Buying starting group · '+count+'/'+slot.seed;
 return 'Wagering toward '+format(slot.target)+' · '+slot.last;
}
export function tick(s,seconds,rng=Math.random){
 seconds=Math.max(0,Math.min(seconds,2));let left=seconds;
 while(left>0){const age=s.idleSeconds??0,edge=age<60?60:age<180?180:Infinity,part=Math.min(left,edge-age);gain(s,activeIncome(s)*part);s.idleSeconds=age+part;left-=part;}
 s.playtime+=seconds;
 for(const slot of s.slots){if(!slot.enabled)continue;const n=s.counts[slot.thinker];if(n>=slot.target){slot.enabled=false;slot.last='Target reached';continue;}slot.buyTimer+=seconds;slot.wagerTimer+=seconds;
  if(n<slot.seed){if(slot.buyTimer>=3/(1+slot.buySpeed*.65)){slot.buyTimer=0;slot.last=buy(s,slot.thinker)?'Bought one':'Waiting for thoughts';}continue;}
  if(slot.wagerTimer>=5/(1+slot.wagerSpeed*.45)){slot.wagerTimer=0;const r=wager(s,slot.thinker,rng,slot);slot.last=r?.win?'Won · doubled':'Lost · buying again';if(s.counts[slot.thinker]>=slot.target)slot.enabled=false;}
 }
 return checkAchievements(s);
}
export function offline(s,now=Date.now()){
 const elapsed=Math.max(0,(now-s.savedAt)/1000),seconds=Math.min(3600,elapsed),ceiling=Number.isFinite(eraCost(s))?eraCost(s)*.1:rate(s)*36;
 const n=Math.min(rate(s)*seconds*.01,ceiling);gain(s,n);s.idleSeconds=(s.idleSeconds??0)+elapsed;s.savedAt=now;s.lastClick=0;s.challenge=null;s.paradox=null;return {seconds,thoughts:n};
}
export function transcend(s){const wisdom=wisdomGain(s);if(!wisdom)return false;const n=fresh();for(const key of ['lifetime','wisdom','ink','truths','achievements','runs','clicks','wins','losses','highestEra','policeWins','paradoxWins','playtime','wagerStats'])n[key]=structuredClone(s[key]);n.wisdom+=wisdom;n.ink+=Math.max(1,Math.floor(wisdom/2));n.runs++;if(n.truths.includes(0)){n.thoughts=300;n.counts[1]=1;n.discovered[1]=true;}Object.assign(s,n);return {wisdom,ink:Math.max(1,Math.floor(wisdom/2))};}
export function buyTruth(s,i){const t=TRUTHS[i];if(!t||s.truths.includes(i)||s.ink<t.cost)return false;s.ink-=t.cost;s.truths.push(i);engage(s);return true;}
export const synthesisCost=s=>Math.round(8*1.28**s.synthesis);
export function synthesize(s){const amount=synthesisCost(s),limit=s.truths.includes(5)?30:20;if(s.era<12||s.synthesis>=limit||s.insight<50||![2,7,12].every(i=>s.counts[i]>=amount))return false;[2,7,12].forEach(i=>s.counts[i]-=amount);s.insight-=50;s.synthesis++;engage(s);return true;}
export function validateState(input){if(!input||typeof input!=='object'||input.version!==1)throw Error('This is not a compatible Philosophy save.');const s=fresh();for(const k of Object.keys(s)){if(input[k]!==undefined)s[k]=structuredClone(input[k]);}const bounded=(v,max=1e100)=>typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=max;for(const k of ['thoughts','run','lifetime','wisdom','ink','runs','clicks','wins','losses','policeWins','paradoxWins','playtime','savedAt','policeAt','paradoxAt','lastClick','idleSeconds'])if(!bounded(s[k]))throw Error('Invalid save values.');for(const [k,max] of [['era',14],['highestEra',14],['meta',5],['focus',20],['odds',8],['synthesis',30],['insight',100]])if(!bounded(s[k],max)||!Number.isInteger(s[k]))throw Error('Invalid progression.');if(!Array.isArray(s.counts)||s.counts.length!==15||!s.counts.every(n=>bounded(n,MAX_COUNT)&&Number.isInteger(n)))throw Error('Invalid thinkers.');if(!Array.isArray(s.discovered)||s.discovered.length!==15||!s.discovered.every(x=>typeof x==='boolean'))throw Error('Invalid discoveries.');for(const [k,max] of [['truths',5],['achievements',29]]){if(!Array.isArray(s[k])||!s[k].every(x=>Number.isInteger(x)&&x>=0&&x<=max)||new Set(s[k]).size!==s[k].length)throw Error('Invalid collection.');}if(!Array.isArray(s.slots)||s.slots.length>3)throw Error('Invalid automation.');const seen=new Set();for(const slot of s.slots){if(!Number.isInteger(slot.thinker)||slot.thinker<0||slot.thinker>14||!s.discovered[slot.thinker]||seen.has(slot.thinker)||typeof slot.enabled!=='boolean'||!Number.isInteger(slot.seed)||slot.seed<1||slot.seed>32||!Number.isInteger(slot.target)||slot.target<=slot.seed||slot.target>MAX_COUNT)throw Error('Invalid automation settings.');seen.add(slot.thinker);for(const k of ['buySpeed','wagerSpeed','luck'])if(!Number.isInteger(slot[k])||slot[k]<0||slot[k]>4)throw Error('Invalid automation upgrades.');slot.buyTimer=0;slot.wagerTimer=0;slot.last='Ready';}if(!input.wagerStats)s.wagerStats={manualWins:0,manualLosses:0,autoWins:0,autoLosses:0,legacyWins:s.wins,legacyLosses:s.losses};
const ws=s.wagerStats;if(!ws||typeof ws!=='object'||!['manualWins','manualLosses','autoWins','autoLosses','legacyWins','legacyLosses'].every(k=>Number.isSafeInteger(ws[k])&&ws[k]>=0)||ws.manualWins+ws.autoWins+ws.legacyWins!==s.wins||ws.manualLosses+ws.autoLosses+ws.legacyLosses!==s.losses)throw Error('Invalid wager records.');
s.challenge=null;s.paradox=null;return s;}
export function format(n){if(!Number.isFinite(n))return '—';if(n<1000)return n<10?n.toFixed(1).replace('.0',''):Math.floor(n).toLocaleString();const units=['','K','M','B','T','Qa','Qi','Sx','Sp','Oc','No'];const e=Math.floor(Math.log10(n)/3);return e<units.length?(n/1000**e).toFixed(2).replace(/\.00$/,'')+units[e]:n.toExponential(2);}


